version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mecstock_db
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 8080
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgres://your_username:your_password@db:5432/mecstock_db
  #   ports:
  #     - "8000:8000"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - backend
