# Generated by Django 4.2 on 2025-06-18 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_servico_ativo_servico_status_atual"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="home_service",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servico",
            name="service_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Endereço onde o serviço será realizado (apenas para serviços domiciliares)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servicos_realizados",
                to="core.endereco",
            ),
        ),
    ]
